import { Application, Contact } from '../types';

export const INITIAL_SAMPLE_APPLICATIONS: Omit<Application, 'id' | 'userId'>[] = [
  {
    company: 'Linear',
    role: 'Senior Frontend Engineer',
    platform: 'Company Site',
    workLocation: 'Hybrid',
    employmentType: 'Full-time',
    location: 'San Francisco, CA',
    dateApplied: '2026-07-15',
    status: 'Interview',
    jobLink: 'https://linear.app/careers/senior-frontend-engineer',
    contactEmail: 'karla@linear.app',
    contacts: [
      {
        id: 'c1',
        name: 'Karla Lindqvist',
        role: 'Tech Talent Lead',
        email: 'karla@linear.app',
        phone: '+1 415-555-0144',
        linkedIn: 'https://linkedin.com/in/karlaindqvist',
        notes: 'Very friendly, responds promptly via email.'
      },
      {
        id: 'c2',
        name: 'Tuomas Artman',
        role: 'Co-founder & CTO',
        email: 'tuomas@linear.app'
      }
    ],
    tasks: [
      { id: 't1', title: 'Complete take-home design system assignment', completed: true, dueDate: '2026-07-19' },
      { id: 't2', title: 'Prepare architecture deck for Thursday panel', completed: false, dueDate: '2026-07-28' },
      { id: 't3', title: 'Send follow-up thank you email to Karla', completed: false }
    ],
    notes: 'Completed technical take-home design system task. Scheduled system design panel on Thursday.',
    emails: [
      { id: 'em1', subject: 'Interview Confirmation — System Design Panel', sender: 'karla@linear.app', date: 'Jul 20', snippet: 'Hi! We are excited to move forward with the system design interview...' },
      { id: 'em2', subject: 'Next Steps: Technical Take-Home Review', sender: 'karla@linear.app', date: 'Jul 16', snippet: 'Thanks for applying! Here is your assignment link...' }
    ],
    stageUpdatedAt: '2026-07-20T10:00:00Z',
    createdAt: '2026-07-15T09:00:00Z',
    updatedAt: '2026-07-20T10:00:00Z',
  },
  {
    company: 'Stripe',
    role: 'Staff Product Engineer',
    platform: 'Referral',
    workLocation: 'Hybrid',
    employmentType: 'Full-time',
    location: 'Seattle, WA',
    dateApplied: '2026-07-10',
    status: 'Offer',
    jobLink: 'https://stripe.com/jobs/staff-product-engineer',
    contactEmail: 'alex.recruiter@stripe.com',
    contacts: [
      {
        id: 'c3',
        name: 'Alex Rivera',
        role: 'Senior Staff Recruiter',
        email: 'alex.recruiter@stripe.com',
        phone: '+1 650-555-0199',
        linkedIn: 'https://linkedin.com/in/alexriverastripe',
        notes: 'Primary point of contact for offer negotiations and benefits package.'
      },
      {
        id: 'c4',
        name: 'David Chen',
        role: 'Engineering Director',
        email: 'dchen@stripe.com',
        notes: 'Hiring manager for Billing Infrastructure.'
      }
    ],
    tasks: [
      { id: 't4', title: 'Review offer breakdown (Base + Equity + Signing bonus)', completed: true },
      { id: 't5', title: 'Schedule call with David Chen regarding team placement', completed: true, dueDate: '2026-07-25' },
      { id: 't6', title: 'Sign and return official offer agreement', completed: false, dueDate: '2026-07-30' }
    ],
    notes: 'Written offer received! $215k base + equity. Discussing start date and team matching.',
    stageUpdatedAt: '2026-07-24T15:30:00Z',
    createdAt: '2026-07-10T11:00:00Z',
    updatedAt: '2026-07-24T15:30:00Z',
  },
  {
    company: 'Vercel',
    role: 'UI Platform Engineer',
    platform: 'Otta',
    workLocation: 'Remote',
    employmentType: 'Full-time',
    location: 'New York, NY',
    dateApplied: '2026-07-18',
    status: 'Screening',
    jobLink: 'https://vercel.com/careers/ui-platform',
    contactEmail: 'sarah.miller@vercel.com',
    contacts: [
      {
        id: 'c5',
        name: 'Sarah Miller',
        role: 'Technical Recruiter',
        email: 'sarah.miller@vercel.com',
        phone: '+1 415-555-8822'
      }
    ],
    tasks: [
      { id: 't7', title: 'Initial recruiter screening call', completed: true, dueDate: '2026-07-21' },
      { id: 't8', title: 'Practice live Next.js Server Components coding scenario', completed: false, dueDate: '2026-07-29' }
    ],
    notes: 'Recruiter call with Sarah went great. Next step is 45-min coding screen with team lead.',
    stageUpdatedAt: '2026-07-22T14:00:00Z',
    createdAt: '2026-07-18T16:20:00Z',
    updatedAt: '2026-07-22T14:00:00Z',
  },
  {
    company: 'Figma',
    role: 'Design Systems Engineer',
    platform: 'LinkedIn',
    workLocation: 'Onsite',
    employmentType: 'Full-time',
    location: 'New York, NY',
    dateApplied: '2026-07-12',
    status: 'Interview',
    jobLink: 'https://figma.com/careers/dse',
    contactEmail: 'jordan.careers@figma.com',
    contacts: [
      {
        id: 'c6',
        name: 'Jordan Lee',
        role: 'Lead Talent Partner',
        email: 'jordan.careers@figma.com',
        linkedIn: 'https://linkedin.com/in/jordanleefigma'
      }
    ],
    tasks: [
      { id: 't9', title: 'Review HTML Canvas & WebGL performance fundamentals', completed: true },
      { id: 't10', title: 'Onsite loop preparation with design system mock projects', completed: false, dueDate: '2026-07-28' }
    ],
    notes: 'Onsite loop scheduled for next Tuesday. 4 rounds: Canvas rendering, Component APIs, Architecture, Culture.',
    stageUpdatedAt: '2026-07-21T09:15:00Z',
    createdAt: '2026-07-12T13:10:00Z',
    updatedAt: '2026-07-21T09:15:00Z',
  },
  {
    company: 'Supabase',
    role: 'Full Stack Engineer (Realtime)',
    platform: 'Lever',
    workLocation: 'Remote',
    employmentType: 'Full-time',
    location: 'Remote — Worldwide',
    dateApplied: '2026-07-20',
    status: 'Screening',
    jobLink: 'https://supabase.com/careers/fullstack-realtime',
    notes: 'Applied with custom Elixir/React demo link in cover note.',
    stageUpdatedAt: '2026-07-23T11:00:00Z',
    createdAt: '2026-07-20T08:30:00Z',
    updatedAt: '2026-07-23T11:00:00Z',
  },
  {
    company: 'Raycast',
    role: 'Desktop Application Engineer',
    platform: 'Company Site',
    workLocation: 'Remote',
    employmentType: 'Full-time',
    location: 'Remote — Europe',
    dateApplied: '2026-07-22',
    status: 'Applied',
    jobLink: 'https://raycast.com/jobs/desktop-engineer',
    notes: 'Submitted application via website portal.',
    stageUpdatedAt: '2026-07-22T10:00:00Z',
    createdAt: '2026-07-22T10:00:00Z',
    updatedAt: '2026-07-22T10:00:00Z',
  },
  {
    company: 'OpenAI',
    role: 'Member of Technical Staff - UI',
    platform: 'Greenhouse',
    workLocation: 'Onsite',
    employmentType: 'Full-time',
    location: 'San Francisco, CA',
    dateApplied: '2026-07-05',
    status: 'Interview',
    jobLink: 'https://openai.com/careers/mts-ui',
    notes: 'Passed initial technical screen. Deep dive into streaming AI token rendering mechanics.',
    stageUpdatedAt: '2026-07-19T18:00:00Z',
    createdAt: '2026-07-05T14:45:00Z',
    updatedAt: '2026-07-19T18:00:00Z',
  },
  {
    company: 'Anthropic',
    role: 'Frontend Engineer - Claude Web',
    platform: 'Greenhouse',
    workLocation: 'Hybrid',
    employmentType: 'Full-time',
    location: 'San Francisco, CA',
    dateApplied: '2026-07-08',
    status: 'Screening',
    jobLink: 'https://anthropic.com/careers/frontend-claude',
    notes: 'Screening call booked for Friday morning.',
    stageUpdatedAt: '2026-07-21T16:00:00Z',
    createdAt: '2026-07-08T12:00:00Z',
    updatedAt: '2026-07-21T16:00:00Z',
  },
  {
    company: 'Datadog',
    role: 'Senior Software Engineer - APM Dashboards',
    platform: 'LinkedIn',
    workLocation: 'Hybrid',
    employmentType: 'Full-time',
    location: 'New York, NY',
    dateApplied: '2026-06-28',
    status: 'Rejected',
    jobLink: 'https://datadog.com/careers',
    notes: 'Role filled internally. Received standard automated response.',
    stageUpdatedAt: '2026-07-10T12:00:00Z',
    createdAt: '2026-06-28T09:00:00Z',
    updatedAt: '2026-07-10T12:00:00Z',
  },
  {
    company: 'GitHub',
    role: 'Senior Frontend Developer - Actions UI',
    platform: 'Referral',
    workLocation: 'Remote',
    employmentType: 'Full-time',
    location: 'Remote — US',
    dateApplied: '2026-07-14',
    status: 'Offer',
    jobLink: 'https://github.com/about/careers',
    notes: 'Verbal offer confirmed! Reviewing health benefits and remote stipend details.',
    stageUpdatedAt: '2026-07-25T11:00:00Z',
    createdAt: '2026-07-14T10:30:00Z',
    updatedAt: '2026-07-25T11:00:00Z',
  },
  {
    company: 'Notion',
    role: 'Product Engineer - Editor Team',
    platform: 'Otta',
    workLocation: 'Hybrid',
    employmentType: 'Full-time',
    location: 'San Francisco, CA',
    dateApplied: '2026-07-01',
    status: 'Interview',
    jobLink: 'https://notion.so/careers',
    notes: 'Pair programming round on custom contenteditable extensions.',
    stageUpdatedAt: '2026-07-16T15:00:00Z',
    createdAt: '2026-07-01T14:00:00Z',
    updatedAt: '2026-07-16T15:00:00Z',
  },
  {
    company: 'Cloudflare',
    role: 'Systems & UI Developer',
    platform: 'LinkedIn',
    workLocation: 'Hybrid',
    employmentType: 'Full-time',
    location: 'Austin, TX',
    dateApplied: '2026-07-21',
    status: 'Applied',
    jobLink: 'https://cloudflare.com/careers',
    notes: 'Applied via easy apply on LinkedIn.',
    stageUpdatedAt: '2026-07-21T17:00:00Z',
    createdAt: '2026-07-21T17:00:00Z',
    updatedAt: '2026-07-21T17:00:00Z',
  },
  {
    company: 'Retool',
    role: 'Frontend Engineer - Core Components',
    platform: 'Lever',
    workLocation: 'Hybrid',
    employmentType: 'Full-time',
    location: 'San Francisco, CA',
    dateApplied: '2026-07-16',
    status: 'Applied',
    jobLink: 'https://retool.com/careers',
    notes: 'Awaiting recruiter review.',
    stageUpdatedAt: '2026-07-16T13:00:00Z',
    createdAt: '2026-07-16T13:00:00Z',
    updatedAt: '2026-07-16T13:00:00Z',
  },
  {
    company: 'Shopify',
    role: 'Senior Developer - Checkout Experience',
    platform: 'Company Site',
    workLocation: 'Remote',
    employmentType: 'Full-time',
    location: 'Remote — Americas',
    dateApplied: '2026-06-25',
    status: 'Archived',
    jobLink: 'https://shopify.com/careers',
    notes: 'Decided not to pursue due to timezone difference.',
    stageUpdatedAt: '2026-07-05T09:00:00Z',
    createdAt: '2026-06-25T11:00:00Z',
    updatedAt: '2026-07-05T09:00:00Z',
  },
  {
    company: 'Ramp',
    role: 'Product Engineer - Expense Controls',
    platform: 'Otta',
    workLocation: 'Onsite',
    employmentType: 'Full-time',
    location: 'New York, NY',
    dateApplied: '2026-07-19',
    status: 'Applied',
    jobLink: 'https://ramp.com/careers',
    notes: 'Referred by former teammate.',
    stageUpdatedAt: '2026-07-19T10:00:00Z',
    createdAt: '2026-07-19T10:00:00Z',
    updatedAt: '2026-07-19T10:00:00Z',
  },
  {
    company: 'Vanta',
    role: 'Staff Frontend Engineer',
    platform: 'Lever',
    workLocation: 'Hybrid',
    employmentType: 'Full-time',
    location: 'San Francisco, CA',
    dateApplied: '2026-07-11',
    status: 'Screening',
    jobLink: 'https://vanta.com/careers',
    notes: 'Hiring manager screen scheduled.',
    stageUpdatedAt: '2026-07-18T14:30:00Z',
    createdAt: '2026-07-11T12:00:00Z',
    updatedAt: '2026-07-18T14:30:00Z',
  },
  {
    company: 'Docker',
    role: 'Senior Web Engineer',
    platform: 'Indeed',
    workLocation: 'Remote',
    employmentType: 'Contract',
    location: 'Palo Alto, CA',
    dateApplied: '2026-06-20',
    status: 'Rejected',
    jobLink: 'https://docker.com/careers',
    notes: 'Position closed after initial screening.',
    stageUpdatedAt: '2026-07-02T10:00:00Z',
    createdAt: '2026-06-20T15:00:00Z',
    updatedAt: '2026-07-02T10:00:00Z',
  },
  {
    company: 'GitLab',
    role: 'Frontend Engineer - CI/CD UX',
    platform: 'Company Site',
    workLocation: 'Remote',
    employmentType: 'Full-time',
    location: 'Remote — Worldwide',
    dateApplied: '2026-07-23',
    status: 'Applied',
    jobLink: 'https://gitlab.com/jobs',
    notes: 'Asynchronous screening questions submitted.',
    stageUpdatedAt: '2026-07-23T11:20:00Z',
    createdAt: '2026-07-23T11:20:00Z',
    updatedAt: '2026-07-23T11:20:00Z',
  },
  {
    company: 'Postman',
    role: 'Senior UI Architect',
    platform: 'LinkedIn',
    workLocation: 'Remote',
    employmentType: 'Full-time',
    location: 'Bengaluru, IN',
    dateApplied: '2026-07-17',
    status: 'Applied',
    jobLink: 'https://postman.com/careers',
    notes: 'Submitted application.',
    stageUpdatedAt: '2026-07-17T16:00:00Z',
    createdAt: '2026-07-17T16:00:00Z',
    updatedAt: '2026-07-17T16:00:00Z',
  },
  {
    company: 'Slack',
    role: 'Senior Frontend Engineer - Desktop',
    platform: 'Greenhouse',
    workLocation: 'Hybrid',
    employmentType: 'Full-time',
    location: 'San Francisco, CA',
    dateApplied: '2026-07-13',
    status: 'Interview',
    jobLink: 'https://slack.com/careers',
    notes: 'Architecture & Electron performance interview scheduled.',
    stageUpdatedAt: '2026-07-22T09:00:00Z',
    createdAt: '2026-07-13T10:00:00Z',
    updatedAt: '2026-07-22T09:00:00Z',
  },
  {
    company: 'Atlassian',
    role: 'Senior Frontend Engineer - Jira Service',
    platform: 'Company Site',
    workLocation: 'Remote',
    employmentType: 'Part-time',
    location: 'Sydney, AU',
    dateApplied: '2026-07-03',
    status: 'Archived',
    jobLink: 'https://atlassian.com/careers',
    notes: 'Archived due to accepting another offer track.',
    stageUpdatedAt: '2026-07-15T12:00:00Z',
    createdAt: '2026-07-03T09:00:00Z',
    updatedAt: '2026-07-15T12:00:00Z',
  },
  {
    company: 'Netflix',
    role: 'UI Engineer - Member Experience',
    platform: 'Referral',
    workLocation: 'Onsite',
    employmentType: 'Full-time',
    location: 'Los Gatos, CA',
    dateApplied: '2026-07-09',
    status: 'Screening',
    jobLink: 'https://jobs.netflix.com',
    notes: 'Recruiter call finished. Waiting for engineering manager sync.',
    stageUpdatedAt: '2026-07-17T11:00:00Z',
    createdAt: '2026-07-09T14:00:00Z',
    updatedAt: '2026-07-17T11:00:00Z',
  },
  {
    company: 'Spotify',
    role: 'Senior Web Engineer - Web Player',
    platform: 'Greenhouse',
    workLocation: 'Hybrid',
    employmentType: 'Full-time',
    location: 'New York, NY',
    dateApplied: '2026-07-24',
    status: 'Applied',
    jobLink: 'https://lifeatspotify.com/jobs',
    notes: 'Applied via company site.',
    stageUpdatedAt: '2026-07-24T08:00:00Z',
    createdAt: '2026-07-24T08:00:00Z',
    updatedAt: '2026-07-24T08:00:00Z',
  },
];

export const INITIAL_SAMPLE_CONTACTS: Omit<Contact, 'id' | 'userId'>[] = [
  {
    name: 'Karla Lindqvist',
    role: 'Tech Talent Lead',
    organization: 'Linear',
    category: 'Recruiter',
    email: 'karla@linear.app',
    phone: '+1 415-555-0144',
    linkedIn: 'https://linkedin.com/in/karlaindqvist',
    notes: 'Very friendly, responds promptly via email. Coordinating system design panel.',
    applicationIds: [],
    createdAt: '2026-07-15T09:00:00Z',
    updatedAt: '2026-07-20T10:00:00Z',
  },
  {
    name: 'Tuomas Artman',
    role: 'Co-founder & CTO',
    organization: 'Linear',
    category: 'Hiring Manager',
    email: 'tuomas@linear.app',
    notes: 'Key decision maker for frontend architecture team.',
    applicationIds: [],
    createdAt: '2026-07-15T09:00:00Z',
    updatedAt: '2026-07-15T09:00:00Z',
  },
  {
    name: 'Alex Rivera',
    role: 'Senior Staff Recruiter',
    organization: 'Stripe',
    category: 'Recruiter',
    email: 'alex.recruiter@stripe.com',
    phone: '+1 650-555-0199',
    linkedIn: 'https://linkedin.com/in/alexriverastripe',
    notes: 'Primary point of contact for offer negotiations and benefits package.',
    applicationIds: [],
    createdAt: '2026-07-10T11:00:00Z',
    updatedAt: '2026-07-24T15:30:00Z',
  },
  {
    name: 'David Chen',
    role: 'Engineering Director',
    organization: 'Stripe',
    category: 'Hiring Manager',
    email: 'dchen@stripe.com',
    notes: 'Hiring manager for Billing Infrastructure.',
    applicationIds: [],
    createdAt: '2026-07-10T11:00:00Z',
    updatedAt: '2026-07-24T15:30:00Z',
  },
  {
    name: 'Elena Rostova',
    role: 'Principal Architect & Career Mentor',
    organization: 'Tech Mentorship Network',
    category: 'Mentor',
    email: 'elena.rostova@mentors.dev',
    phone: '+1 206-555-0188',
    linkedIn: 'https://linkedin.com/in/elenarostova-mentor',
    notes: 'Monthly 1:1 strategy sessions on executive presence, salary negotiation, and system design interviews.',
    nextFollowUpDate: new Date(Date.now() + 86400000).toISOString().slice(0, 10),
    applicationIds: [],
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-07-25T14:00:00Z',
  },
  {
    name: 'Marcus Vance',
    role: 'Staff Frontend Engineer',
    organization: 'Supabase Alumni',
    category: 'Peer / Alumni',
    email: 'marcus.vance@alumni.dev',
    linkedIn: 'https://linkedin.com/in/marcusvance',
    notes: 'College classmate. Offered referral for upcoming senior engineer headcount.',
    nextFollowUpDate: new Date(Date.now() + 86400000 * 3).toISOString().slice(0, 10),
    applicationIds: [],
    createdAt: '2026-07-05T12:00:00Z',
    updatedAt: '2026-07-20T08:00:00Z',
  },
];

import { calculateDaysInStage } from './dateUtils';

export { calculateDaysInStage };
